language: python
python: 2.7
env:
  - TOX_ENV=flake8
  - TOX_ENV=py35-dj111
  - TOX_ENV=py35-dj110
  - TOX_ENV=py35-dj19
  - TOX_ENV=py35-dj18
  - TOX_ENV=py27-dj111
  - TOX_ENV=py27-dj110
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj15

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
